# Generated by Django 5.1.1 on 2024-10-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
        ('products', '0008_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='prebuilt_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='domains',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='landing_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('landing_source', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('url_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.domain_path')),
            ],
        ),
    ]
