# Generated by Django 5.1.1 on 2024-09-16 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_created_at_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 12, 44, 17, 851464)),
        ),
    ]
